[DEFAULT]
# Define POD number
# PHFileVersionName = 25.10.4.1
# PHFileEnvName = P2MA_PLATQA

POD = 2
# Platform code path
EXECUTABLEPATH_DRIVE = D:
EXECUTABLEPATH = D:\CC_Runtime
# KMS name
emKMSdefaultMachines = CCKMSE1PATQAB1 CCKMSE1PATQAB2
# KMS name DR
emKMSdefaultMachinesDR = CCKMSW2PATQAB1 CCKMSW2PATQAB2
# Database authentication mode
authenticationMode = WA
# smtp server for LOCAL
SMTP_SERVER = DUMMY
# smtp server for DR
SMTP_SERVER_DR = 
# smtp port for LOCAL
SMTP_PORT = 25
# Database server name
DB_Server_NAME = CCAPPLIST1
# DSN name
DB_DSN_NAME = LISTPLAT
# Database server login
post_dbms_login = wa
# Database server password
post_dbms_passwd = windowslogin
# Database names
DBName_CI = CCGS_CoreIssue
DBName_CC = CCGS_CoreCollect 
DBName_CL = CCGS_CoreLibrary
DBName_CAuth = CCGS_CoreAuth
DBName_CoreApp = CCGS_CoreApp 
DBName_CoreCredit = CCGS_CoreCredit 
DBName_Portal =
# Reporting Database names
DB_Server_NAME_RPT  = CCRPTLIST1
DB_DSN_NAME_RPT  = LISTRPT
post_dbms_login_RPT  = wa
post_dbms_passwd_RPT  = windowslogin
# Reporting Database names
DBName_CI_RPT  = CCGS_RPT_CoreIssue
DBName_CC_RPT  = CCGS_RPT_CoreCollect
DBName_CL_RPT  = CCGS_RPT_CoreLibrary
DBName_CAuth_RPT  = CCGS_RPT_CoreAuth
DBName_CoreApp_RPT  = CCGS_RPT_CoreApp
DBName_CoreCredit_RPT  = CCGS_RPT_CoreCredit
# AWS simple email service
ses_smtp_secret_name = ses-smtp-patqa-secret
ses_smtp_url = email-smtp.us-east-1.amazonaws.com
ses_region_name = us-east-1
# For starttls / TLS - 587, For SSL - 465
ses_smtp_port = 587
# email source can be LOCAL / AWS
alert_email_source = AWS
# Alert email addresses
alert_email_sender = pod2-patqa-alerts@infra.marcus.com
# ACH Outgoing Process Setup
# BatchScripts folder path
BatchScripts = D:\DBBSetup\BatchScripts\CoreIssue
# CheckPIIData  =  0 (Disable PII Hub), CheckPIIData  =  1 (Enable PII Hub)
# For Production it should be 1
CheckPIIData = 0
# Environment name of PII Hub
PIIHubEnv = PATQA
# If need to generate Merchant Settlement ACH, set flag to 1
MerchantACHSettlement = 0
# CheckACHScheduleSetup (1 - PLAT Production)
CheckACHScheduleSetup = 0
# 1 - CCard2Flag (Insert Payments into CCard_Priamry2)
CCard2Flag = 0
# In ACH file generation, by pass validation of record type 9 values should be YES/NO
ByPassValidation = YES
# Plat ACH Outgoing ACH Environment variables
PLATACHOutgoingFileIN = D:\DBBSetup\Dump\ACH\Outgoing\IN
PLATACHOutgoingFileOUT = D:\DBBSetup\Dump\ACH\Outgoing\OUT
PLATACHOutgoingFileERROR = D:\DBBSetup\Dump\ACH\Outgoing\ERROR
PLATACHOutgoingFileLOG = D:\DBBSetup\Dump\ACH\Outgoing\LOG
PLATACHOutgoingFileIntermediate = D:\DBBSetup\Dump\ACH\Outgoing\Intermediate
# Plat ACH ISO Return
PLATISOACHIncomingFileIN = D:\DBBSetup\Dump\ACH\ACHISOReturn\IN
PLATISOACHIncomingFileOUT = D:\DBBSetup\Dump\ACH\ACHISOReturn\OUT
PLATISOACHIncomingFileERROR = D:\DBBSetup\Dump\ACH\ACHISOReturn\ERROR
PLATISOACHIncomingFileLOG = D:\DBBSetup\Dump\ACH\ACHISOReturn\LOG
# File has will used if YES
ACHISOFileHash = YES
# Plat LockBox
PLATLockBoxIN = D:\DBBSetup\Dump\PLAT\LockBox\IN
PLATLockBoxOUT = D:\DBBSetup\Dump\Plat\LockBox\OUT
PLATLockBoxOUTDR = D:\DBBSetup\Dump\Plat\LockBox\OUT
PLATLockBoxERROR = D:\DBBSetup\Dump\PLAT\LockBox\ERROR
PLATLockBoxLOG = D:\DBBSetup\Dump\PLAT\LockBox\LOG
PLATLockBoxBlankFile = D:\DBBSetup\Dump\PLAT\LockBox\BLANK
PLATLockBoxFileServerPath = D:\DBBSetup\Dump\PLAT\LockBox\OUT
# File has will used if YES
LockBoxFileHash = YES
# Plat BillPayPayment Environment variables
BillPayPaymentIN = D:\DBBSetup\Dump\PLAT\BillPayPayment\IN
BillPayPaymentOUT = D:\DBBSetup\Dump\PLAT\BillPayPayment\OUT
BillPayPaymentERROR = D:\DBBSetup\Dump\PLAT\BillPayPayment\ERROR
BillPayPaymentLOG = D:\DBBSetup\Dump\PLAT\BillPayPayment\LOG
# File has will used if YES
BillPayFileHash = YES
# Plat ACH Incoming ACH Environment variables
PLAT_ACHFileIN = D:\DBBSetup\Dump\ACH\Incoming\IN
PLAT_ACHFileOUT = D:\DBBSetup\Dump\ACH\Incoming\OUT
PLAT_ACHFileOUTDR = D:\DBBSetup\Dump\ACH\Incoming\OUT
PLAT_ACHFileERROR = D:\DBBSetup\Dump\ACH\Incoming\ERROR
PLAT_ACHFileLOG = D:\DBBSetup\Dump\ACH\Incoming\LOG
#PLAT_ACHIncomingFileServerPath = D:\DBBSetup\Dump\ACH\Incoming\OUT
PLAT_ACHIncomingFileServerPath = D:\DBBSetup\Dump\ACH\Incoming\OUT
PLAT_ACHFileBLANKFILE = D:\DBBSetup\Dump\ACH\Incoming\BLANK
# File has will used if YES
ACHReturnFileHash = YES
# CBR File Generation
CBREPORTING_FILE_PATH = D:\DBBSetup\Dump\CBReporting\CBR
CBREPORTING_FILE_PATH_DR = D:\DBBSetup\Dump\CBReporting\CBR
CBR_LogFileFolderName = D:\DBBSetup\Dump\CBReporting\Log
CBR_PIIFileIntermediate = D:\DBBSetup\Dump\CBReporting\Intermediate
CBR_MultipleFiles = D:\DBBSetup\Dump\CBReporting\MultipleFiles
# 10 Lakh (1 Million)
# LoopBatchSize = 1000000
LoopBatchSize = 50000
# 100 Lakh (10 Million)
# MAXRecordInFile = 10000000
MAXRecordInFile = 1000000
CBREmailFrom = pod2-patqa-alerts@infra.marcus.com
CBRNotifyEmail  =  Pod2ConfigTeam@corecard.com, platalertsupport@corecard.com, PlatOperation@corecard.com
CBR_ERRORFileFolderName = D:\DBBSetup\Dump\CBReporting\ERROR
CBR_WithPIIFileFolderName = D:\DBBSetup\Dump\CBReporting\CBR_WithPII
CBR_WithoutPIIFileFolderName = D:\DBBSetup\Dump\CBReporting\CBR_WithoutPII
# Set GetCBRFilesFromDB as 1 if validation from database needs to be apply on CBR Files
GetCBRFilesFromDB = 0
# ForceFileGeneration | 0 - Stop file generation if missing PII found, 1 - File generation anyway
ForceFileGeneration = 0
# BCP Approach On(1), BCP Approach Off(0)
EnableCBRBCP = 0

IPMFileIN=D:\DBBSetup\Dump\MasterCard\IPMSettlement\Incoming\T120
IPMFileOUT=D:\DBBSetup\Dump\MasterCard\IPMSettlement\Incoming\OUT
IPM_LOG=D:\DBBSetup\Dump\MasterCard\IPMSettlement\Incoming\LOG
IPM_ERROR=D:\DBBSetup\Dump\MasterCard\IPMSettlement\Incoming\ERROR
IPMJSONCreatedFileLocation=D:\DBBSetup\Dump\MasterCard\IPMSettlement\Incoming\IPMJSON
IPMFileArchive=D:\DBBSetup\Dump\MasterCard\IPMSettlement\Incoming\T120\Archive

MailServerName_StlRcn=Email-smtp.us-east-1.amazonaws.com
MailSender_StlRcn=pod2-patqa-alerts@infra.marcus.com
# MailReceiver_StlRcn=pod1configteam@corecard.com,servicegroup@corecard.com
MailReceiver_StlRcn=pod2configteam@corecard.com,servicegroup@corecard.com,platalert@corecard.com
MultiPODEnabled_IPM =1
JSONReadFileLocation =D:\DBBSetup\Dump\MasterCard\IPMSettlement\Incoming\OUT\
################# Below section must be at bottom of config file #####################
# alert receiver mail Ids can be different for each process
# This section will use to keep alert receiver mail Ids separate for each process
#SQL ODBC Driver Name, Need to check from C:\Windows\SysWOW64\odbcad32 >> System DSN
SqlOdbcDriver = ODBC Driver 17 for SQL Server
#This variable should contain all file Extensions in the sequence they arrive in Production Environment
#In Lower/POD_2 Environments, file sequence should be as per file sequence of that env, e.g. A004,A005,A006,A001,A002
IPMFileSequence = A004,A005,A006,A001
issystemdatetimeenabled_ipm = 1
ACHISOReturnTxnBatchSize = 10

ses_service_name = secretsmanager
# AWS Environment Flag 0 -> FALSE 1 -> TRUE 
AWSEnvironment = 0
ODBC_Driver = ODBC Driver 17 for SQL Server
Cnst_API_url = https://coreissue-blue.patqa.api.cc-pod2.infra.marcus.com/CoreCardServices/CoreCardServices.svc/
APIUserID = DRPSeriveCall
APIPassword = Test123!

# JAZZ CTPFile Environment variables
CTPFileIN = D:\DBBSetup\Dump\CTPFile\IN
CTPFileOUT = D:\DBBSetup\Dump\CTPFile\OUT
CTPFileERROR = D:\DBBSetup\Dump\CTPFile\ERROR
CTPFileLOG = D:\DBBSetup\Dump\CTPFile\LOG
CTPFileBLANK = D:\DBBSetup\Dump\CTPFile\BLANK
CTPFileSLIMFILE = D:\DBBSetup\Dump\CTPFile\SLIMFILE
# File has will used if YES
CTPFileHash = YES

ACHISO_PATH = D:\DBBSetup\Dump\ACH\ACHISOReturnFileGeneration\IN
ACHISO_LOG = D:\DBBSetup\Dump\ACH\ACHISOReturnFileGeneration\LOG

# Plat BillPayPayment Environment variables
BillPayPaymentIntermediate = D:\DBBSetup\Dump\Plat\BillPayPayment\Intermediate
BillPayPaymentException = D:\DBBSetup\Dump\Plat\BillPayPayment\EXCEPTION
BillPayExceptionFile = _Ex
# 0 - False 1 - True
CheckForCutOffTime = 1
Sharding = 0
# Exception File 
ExceptionFilePrefix = EXCP_
#1 parsing through SQL, and 0 parsing through Splitter
ACHISOReturnSQLParsing = 1
#Plat LockBox Environment variables
PLATLockBoxException = D:\DBBSetup\Dump\Plat\LockBox\EXCEPTION
#EXCEPTION file name 
LockboxExceptionFile = _Ex
CBRFile_WithPII_To_WithoutPII = 1
CBR_PreTransmission  =  D:\DBBSetup\Dump\Plat\CBR\CBReporting\PreTransmissionReport
CBR_IDTheftRecon  =  D:\DBBSetup\Dump\Plat\CBR\CBReporting\IDTheftReconReport

#[Embossing]
#IrvingEmbossingEntry
OutGoing_Emb_In=D:\DBBSetup\Dump\OutgoingFiles\IRVING
OutGoing_Emb_Error_Dir=D:\DBBSetup\Dump\OutgoingFiles\IRVING\ERROR
OutGoing_Emb_Processed=D:\DBBSetup\Dump\OutgoingFiles\IRVING\OUT
OutGoing_Emb_Log_Dir=D:\DBBSetup\Dump\OutgoingFiles\IRVING\LOG
SQLLiteDBPath=D:\DBBSetup\Dump\OutgoingFiles\IRVING\SQLite_DB
InsitutionID = 6969
IrvingReport_FileIN = D:\DBBSetup\Dump\IrvingReport\IN
IrvingReport_FileERROR= D:\DBBSetup\Dump\IrvingReport\ERROR
IrvingReport_FileLOG= D:\DBBSetup\Dump\IrvingReport\LOG
IrvingReport_FileOUT= D:\DBBSetup\Dump\IrvingReport\OUT
IrvingReport_DebugMode= D:\DBBSetup\Dump\IrvingReport\DebugMode
IrvingReport_FileException= D:\DBBSetup\Dump\IrvingReport\Exception
IrvingReport_Logfile_DummyShipping = D:\DBBSetup\Dump\IrvingReport\Logfile_DummyShipping
IrvingReport_FileEmpty= D:\DBBSetup\Dump\IrvingReport\OUT\7200
IrvingReport_DummyFileOUT=D:\DBBSetup\Dump\IrvingReport\IrvingReport_MDW\OUT
IrvingReport_FileIN_MDW=D:\DBBSetup\Dump\IrvingReport\IrvingReport_MDW\IN
IrvingReport_FileLOG_MDW=D:\DBBSetup\Dump\IrvingReport\IrvingReport_MDW\LOG
IrvingReport_FileOUT_MDW=D:\DBBSetup\Dump\IrvingReport\IrvingReport_MDW\OUT
ReportFileName=Shipping filename
EnvironmentName = PATQA
IsEmbReportSplitByInsId = YES
DayDiff=0



AccountUpdate_FileIN = D:\DBBSetup\Dump\WaiveLateFee\IN
AccountUpdate_FileERROR = D:\DBBSetup\Dump\WaiveLateFee\Error
AccountUpdate_FileLOG = D:\DBBSetup\Dump\Dump\WaiveLateFee\Log
AccountUpdate_FileOUT = D:\DBBSetup\Dump\Dump\WaiveLateFee\Out
AccountUpdate_EmptyFolder = D:\DBBSetup\Dump\Dump\WaiveLateFee\Empty
AccountUpdate_DebugMode = D:\DBBSetup\Dump\WaiveLateFee\Empty
ReportTime = 6 

DisableRuleFileLOG = D:\DBBSetup\Dump\TargetList\Log

#Reward Target List WhiteListing
TargetListIN = D:\DBBSetup\Dump\Plat\TargetList\IN
TargetListOUT = D:\DBBSetup\Dump\Plat\TargetList\OUT
TargetListResponse = D:\DBBSetup\Dump\Plat\TargetList\Response
TargetListLOG = D:\DBBSetup\Dump\Plat\TargetList\LOG
TargetListERROR = D:\DBBSetup\Dump\Plat\TargetList\ERROR
EmpfileThreshhold = 22:00

# EmbossingEncrypted Start variable Code
EmbossingEncrypted_OUT  =  D:\DBBSetup\Dump\EmbossingEncrypted\EmbossingEncrypted_OUT
EmbossingEncrypted_Log  =  D:\DBBSetup\Dump\EmbossingEncrypted\EmbossingEncrypted_Log
# If IsRollbackRequired is 1 that means need to rollback and 0 for as per BAU process (PANHash64 AS OLDPANHASH,PANHashKey2 AS NEWPANHASH)
IsRollbackRequired  =  0
# New Parameter
AccountBuyerID_FileIN  =  D:\DBBSetup\Dump\AccountBuyerID\InputFolder
AccountBuyerID_FileOUT  =  D:\DBBSetup\Dump\AccountBuyerID\OutFolder
AccountBuyerID_FileERROR  =  D:\DBBSetup\Dump\AccountBuyerID\ErrorFolder
AccountBuyerID_FileLOG  =  D:\DBBSetup\Dump\AccountBuyerID\LogFolder
AccountBuyerID_ActiveCard  =  D:\DBBSetup\Dump\AccountBuyerID\UpdateEmbossingManualStatus\FilePath\IN
BuyerId_chunk_size  =  50000
BuyerId_Update_chunk_size  =  5
SoldFileID_Reprocess  =  71
Reprocess_Status  =  2
[MilkReplaySchedulesUtility]
alert_email_receiver = platalertsuppert@corecard.com
RetailInputFile = D:\DBBSetup\Dump\MilkReplaySchedules\INPUT
RetailErrorFile = D:\DBBSetup\Dump\MilkReplaySchedules\ERROR
RetailOutFile = D:\DBBSetup\Dump\MilkReplaySchedules\OUT
RetailLogFile = D:\DBBSetup\Dump\MilkReplaySchedules\LOG
RetailInstitutionID = 6981
RetailEnvironment = PATQA
RetailExceptionFile = D:\DBBSetup\Dump\MilkReplaySchedules\EXCEPTION
RetailExceptionFilePrefix = EXCP_
RetailExceptionFileSuffix = _PODID_
BatchCount = 10000
AccountNumberCheck = 1
RetailGeneratedFile = D:\DBBSetup\Dump\MilkReplaySchedules\GENERATED
RetailGeneratedOutputFile = D:\DBBSetup\Dump\MilkReplaySchedules\OUT\GENERATED

[PaymentHoldSetup]
alert_email_receiver = platalertsuppert@corecard.com
POTBInputFile = D:\DBBSetup\Dump\POTB\INPUT
POTBErrorFile = D:\DBBSetup\Dump\POTB\ERROR
POTBOutFile = D:\DBBSetup\Dump\POTB\OUT
POTBLogFile = D:\DBBSetup\Dump\POTB\LOG
POTBIdentifier = ACCOUNTNUMBER
POTBPolicy = G2
POTBEnvironment = PATQA
POTBInstitutionID = 6981
POTBExceptionFile = D:\DBBSetup\Dump\POTB\EXCEPTION
POTBExceptionPrefix = EXCP_
POTBExceptionSuffix = _PODID_

[StatementCreditUtility]
alert_email_receiver = Dummy
InputDir = D:\DBBSetup\Dump\StatementCreditUtility\INPUT
OutputDir = D:\DBBSetup\Dump\StatementCreditUtility\OUTPUT
ErrorDir = D:\DBBSetup\Dump\StatementCreditUtility\ERROR
ResponseDir = D:\DBBSetup\Dump\StatementCreditUtility\RESPONSE
LogDir = D:\DBBSetup\Dump\StatementCreditUtility\LOG
ExceptionDir = D:\DBBSetup\Dump\StatementCreditUtility\EXCEPTION
InputFilePrefix = StatementCredit_
ResponseFilePrefix = StatementCreditNegative_
ValidatorBatchCount = 5000
ProcessingEnvironment = PRODUCTION
CutoffTime = 16:30:00
PostingBatchCount = 100

[TxnHistArch_TSDBO]
LogFilePath = D:\DBBSetup\Dump\TSDBO\LOG
IncomingFiles = D:\DBBSetup\Dump\TSDBO\FilePath\IncomingFiles
OutgoingFiles = D:\DBBSetup\Dump\TSDBO\FilePath\OutgoingFiles
DailyMetaDataFilePath = D:\DBBSetup\Dump\TSDBO\FilePath\DailyMetaDataFile
IncomingFiles_ErrorSummary = D:\DBBSetup\Dump\TSDBO\FilePath\IncomingFiles\Error
AccountIncomingFiles = D:\DBBSetup\Dump\TSDBO\FilePath\Account\IncomingFiles
AccountOutgoingFiles = D:\DBBSetup\Dump\TSDBO\FilePath\Account\OutgoingFiles
AccountIncomingOutFiles = D:\DBBSetup\Dump\TSDBO\FilePath\Account\IncomingOutFiles
MailSub = [PLAT PATQA POD2] - [TSDBO Data Extraction] - [{AlertType}]
MailTo = 
MailCC = 

[StatementFingerPrintBatch]
InputDir = D:\DBBSetup\Dump\StatementFingerPrintBatch\INPUT
OutputDir = D:\DBBSetup\Dump\StatementFingerPrintBatch\OUTPUT
ErrorDir = D:\DBBSetup\Dump\StatementFingerPrintBatch\ERROR
LogDir = D:\DBBSetup\Dump\StatementFingerPrintBatch\LOG
alert_email_receiver = Pod2ConfigTeam@corecard.com, platalertsupport@corecard.com, platsd@corecard.com
batchcount = 500
archive = True
RenameInputFile = False

[ACHProcess]
alert_email_receiver = Pod2ConfigTeam@corecard.com,platalertsupport@corecard.com

[ACHISOReturn]
alert_email_receiver = Pod2ConfigTeam@corecard.com, platalertsupport@corecard.com

[LockBox]
alert_email_receiver = Pod2ConfigTeam@corecard.com,platalertsupport@corecard.com

[BillPay]
alert_email_receiver = Pod2ConfigTeam@corecard.com,platalertsupport@corecard.com

[NACHAReturn]
alert_email_receiver = Pod2ConfigTeam@corecard.com,platalertsupport@corecard.com

[CTPFile]
alert_email_receiver = Pod2ConfigTeam@corecard.com,platalertsupport@corecard.com

#########################################################################################