[DEFAULT]
# Define POD number
POD = 2
# Platform code path
EXECUTABLEPATH_DRIVE = D:
EXECUTABLEPATH = D:\CC_Runtime
# KMS name
emKMSdefaultMachines = CCKMSE1UATB1 CCKMSE1UATB2
# KMS name DR
emKMSdefaultMachinesDR = CCKMSW2UATB1 CCKMSW2UATB2 
# Database authentication mode
authenticationMode = WA
# smtp server for LOCAL
SMTP_SERVER = 
# smtp server for DR
SMTP_SERVER_DR = 
# smtp port for LOCAL
SMTP_PORT = 25
# Database server name
DB_Server_NAME = CCAPPLIST1
# DSN name
DB_DSN_NAME = LISTPLAT
# Database server login
post_dbms_login = wa
# Database server password
post_dbms_passwd = windowslogin
# Database names
DBName_CI = CCGS_CoreIssue
DBName_CC = CCGS_CoreCollect 
DBName_CL = CCGS_CoreLibrary
DBName_CAuth = CCGS_CoreAuth
DBName_CoreApp = CCGS_CoreApp 
DBName_CoreCredit = CCGS_CoreCredit 
DBName_Portal =
#GeneralAPI_V3
ODBC_Driver =ODBC Driver 17 for SQL Server
Cnst_API_url = https://uat-services.api.cc-pod2.infra.marcus.com//CoreCardServices//CoreCardServices.svc//
APIUserID = DRPSeriveCall
APIPassword = Test123!
# AWS simple email service
ses_smtp_secret_name = ses-smtp-uat-secret
ses_smtp_url = email-smtp.us-east-1.amazonaws.com
ses_region_name = us-east-1
ses_service_name = secretsmanager
AWSEnvironment = 0
# For starttls / TLS - 587, For SSL - 465
ses_smtp_port = 587
# email source can be LOCAL / AWS
alert_email_source = AWS
# Alert email addresses
alert_email_sender = pod2-uat-alerts@infra.marcus.com
# BatchScripts folder path
BatchScripts = D:\DBBSetup\BatchScripts\CoreIssue
# CheckPIIData  =  0 (Disable PII Hub), CheckPIIData  =  1 (Enable PII Hub)
# For Production it should be 1
CheckPIIData = 0
# Environment name of PII Hub
PIIHubEnv = UAT
# If need to generate Merchant Settlement ACH, set flag to 1
MerchantACHSettlement = 0
# CheckACHScheduleSetup (1 - PLAT Production)
CheckACHScheduleSetup = 0
# 1 - CCard2Flag (Insert Payments into CCard_Priamry2)
CCard2Flag = 0
# In ACH file generation, by pass validation of record type 9 values should be YES/NO
ByPassValidation = YES
# Plat ACH Outgoing ACH Environment variables
PLATACHOutgoingFileIN = D:\DBBSetup\Dump\ACH\Outgoing\IN
PLATACHOutgoingFileOUT = D:\DBBSetup\Dump\ACH\Outgoing\OUT
PLATACHOutgoingFileERROR = D:\DBBSetup\Dump\ACH\Outgoing\ERROR
PLATACHOutgoingFileLOG = D:\DBBSetup\Dump\ACH\Outgoing\LOG
PLATACHOutgoingFileIntermediate = D:\DBBSetup\Dump\ACH\Outgoing\Intermediate
# Plat ACH ISO Return
PLATISOACHIncomingFileIN = D:\DBBSetup\Dump\ACH\ACHISOReturn\IN
PLATISOACHIncomingFileOUT = D:\DBBSetup\Dump\ACH\ACHISOReturn\OUT
PLATISOACHIncomingFileERROR = D:\DBBSetup\Dump\ACH\ACHISOReturn\ERROR
PLATISOACHIncomingFileLOG = D:\DBBSetup\Dump\ACH\ACHISOReturn\LOG
# File has will used if YES
ACHISOFileHash = YES
# Plat LockBox
PLATLockBoxIN = D:\DBBSetup\Dump\Plat\LockBox\IN
PLATLockBoxOUT = D:\DBBSetup\Dump\Plat\LockBox\OUT
PLATLockBoxOUTDR = D:\DBBSetup\Dump\Plat\LockBox\OUT
PLATLockBoxERROR = D:\DBBSetup\Dump\Plat\LockBox\ERROR
PLATLockBoxLOG = D:\DBBSetup\Dump\Plat\LockBox\LOG
PLATLockBoxBlankFile = D:\DBBSetup\Dump\Plat\LockBox\BLANK
PLATLockBoxFileServerPath = D:\DBBSetup\Dump\Plat\LockBox\OUT
PLATLockBoxException = D:\DBBSetup\Dump\Plat\LockBox\EXCEPTION
LockboxExceptionFile = _Ex
# File has will used if YES
LockBoxFileHash = YES
# Plat BillPayPayment Environment variables
BillPayPaymentIN = D:\DBBSetup\Dump\PLAT\BillPayPayment\IN
BillPayPaymentOUT = D:\DBBSetup\Dump\PLAT\BillPayPayment\OUT
BillPayPaymentERROR = D:\DBBSetup\Dump\PLAT\BillPayPayment\ERROR
BillPayPaymentLOG = D:\DBBSetup\Dump\PLAT\BillPayPayment\LOG
BillPayPaymentIntermediate = D:\DBBSetup\Dump\Plat\BillPayPayment\Intermediate
BillPayPaymentException = D:\DBBSetup\Dump\Plat\BillPayPayment\EXCEPTION
# File has will used if YES
BillPayFileHash = YES
#EXCEPTION file name
BillPayExceptionFile = _Ex

# Plat ACH Incoming ACH Environment variables
PLAT_ACHFileIN = D:\DBBSetup\Dump\ACH\Incoming\IN
PLAT_ACHFileOUT = D:\DBBSetup\Dump\ACH\Incoming\OUT
PLAT_ACHFileOUTDR = D:\DBBSetup\Dump\ACH\Incoming\OUT
PLAT_ACHFileERROR = D:\DBBSetup\Dump\ACH\Incoming\ERROR
PLAT_ACHFileLOG = D:\DBBSetup\Dump\ACH\Incoming\LOG
#PLAT_ACHIncomingFileServerPath = D:\DBBSetup\Dump\ACH\Incoming\OUT
PLAT_ACHIncomingFileServerPath = D:\DBBSetup\Dump\ACH\Incoming\OUT
PLAT_ACHFileBLANKFILE = D:\DBBSetup\Dump\ACH\Incoming\BLANK
# File has will used if YES
ACHReturnFileHash = YES
# CBR File Generation
CBREPORTING_FILE_PATH = D:\DBBSetup\Dump\CBReporting\CBR
CBREPORTING_FILE_PATH_DR = D:\DBBSetup\Dump\CBReporting\CBR
CBR_LogFileFolderName = D:\DBBSetup\Dump\CBReporting\Log
CBR_PIIFileIntermediate = D:\DBBSetup\Dump\CBReporting\Intermediate
CBR_MultipleFiles = D:\DBBSetup\Dump\CBReporting\MultipleFiles
# 10 Lakh (1 Million)
# LoopBatchSize = 1000000
LoopBatchSize = 50000
# 100 Lakh (10 Million)
# MAXRecordInFile = 10000000
MAXRecordInFile = 1000000
CBREmailFrom = pod2-uat-alerts@infra.marcus.com
# POD1 Email recipients
# POD2 Email recipients
# POD4 Email recipients (Cookie POD3)
# POD3 Email recipients (Jazz)
# POD1 Email recipients
# POD2 Email recipients
# POD4 Email recipients (Cookie POD3)
# POD3 Email recipients (Jazz)
CBRNotifyEmail  =  PlatAlertSupport@corecard.com,POD3ConfigTeam@corecard.com,PlatOperation@corecard.com,jazzsupport@corecard.com
# BCP Approach On(1), BCP Approach Off(0)
EnableCBRBCP  =  0
CBR_ERRORFileFolderName = D:\DBBSetup\Dump\CBReporting\ERROR
CBR_WithPIIFileFolderName = D:\DBBSetup\Dump\CBReporting\CBR_WithPII
CBR_WithoutPIIFileFolderName = D:\DBBSetup\Dump\CBReporting\CBR_WithoutPII
# Set GetCBRFilesFromDB as 1 if validation from database needs to be apply on CBR Files
GetCBRFilesFromDB = 0
# ForceFileGeneration | 0 - Stop file generation if missing PII found, 1 - File generation anyway
ForceFileGeneration = 0
# 0 - Old Approach (1. Without PII, 2. With PII), 1 - New Approach (1. With PII, 2. Without PII from With PII)
CBRFile_WithPII_To_WithoutPII = 1
CBR_Remediation = D:\DBBSetup\Dump\CBReporting\CBRRemediation

# IPM Incoming Settlement
IPMFileIN=D:\DBBSetup\Dump\MasterCard\IPMSettlement\Incoming\T120
IPMFileOUT=D:\DBBSetup\Dump\MasterCard\IPMSettlement\Incoming\OUT
IPM_LOG=D:\DBBSetup\Dump\MasterCard\IPMSettlement\Incoming\LOG
IPM_ERROR=D:\DBBSetup\Dump\MasterCard\IPMSettlement\Incoming\ERROR
JSONReadFileLocation=D:\DBBSetup\Dump\MasterCard\IPMSettlement\Incoming\OUT\
MultiPODEnabled_IPM=1
MailServerName_StlRcn=email-smtp.us-east-1.amazonaws.com
MailSender_StlRcn=pod2-uat-alerts@infra.marcus.com
MailReceiver_StlRcn=pod2configteam@corecard.com,platsd@corecard.com

#SQL ODBC Driver Name, Need to check from C:\Windows\SysWOW64\odbcad32 >> System DSN
SqlOdbcDriver = ODBC Driver 17 for SQL Server

#This variable should contain all file Extensions in the sequence they arrive in Production Environment
#In Lower/POD_2 Environments, file sequence should be as per file sequence of that env, e.g. A004,A005,A006,A001,A002
IPMFileSequence = A004,A005,A006,A001,A002

#this IsSystemDateTimeEnabled_IPM = 1 Means CPU Utilization is code active and Current Date Time is stamped Clearingfiles.SystemLastDateTime
IsSystemDateTimeEnabled_IPM = 1

#Adding ACHISOReturnTxnBatchSize  variable  in SetupCIPy.ini for COOKIE-197516- Introducing Batch size to create transactions
ACHISOReturnTxnBatchSize = 10
ACHISOReturnSQLParsing = 1
#[ACHISOReturnPy_Multithread.py] 

#[Embossing]
#IrvingEmbossingEntry
OutGoing_Emb_In = D:\DBBSetup\Dump\Embossing\IRVING
OutGoing_Emb_Error_Dir = D:\DBBSetup\Dump\Embossing\IRVING\ERROR
OutGoing_Emb_Processed = D:\DBBSetup\Dump\Embossing\IRVING\OUT
OutGoing_Emb_Log_Dir = D:\DBBSetup\Dump\Embossing\IRVING\LOG
SQLLiteDBPath = D:\DBBSetup\Dump\Embossing\IRVING\SQLite_DB
InsitutionID  = 6969
CI_DB = CCGS_CoreIssue
CL_DB = CCGS_CoreLibrary
CAuth_DB = CCGS_CoreAuth
SERVERNAME = CCAPPLIST1
IrvingReport_FileIN  =  D:\DBBSetup\Dump\IrvingReport\IN
IrvingReport_FileERROR = D:\DBBSetup\Dump\IrvingReport\Error
IrvingReport_FileLOG = D:\DBBSetup\Dump\IrvingReport\Log
IrvingReport_FileOUT = D:\DBBSetup\Dump\IrvingReport\Out
IrvingReport_DebugMode = D:\pythonfiles\IrvingReport\DebugMode
IrvingReport_FileException = D:\DBBSetup\Dump\IrvingReport\Exception
IrvingReport_Logfile_DummyShipping  =  D:\DBBSetup\Dump\IrvingReport\Logfile_DummyShipping
IrvingReport_FileEmpty =  D:\DBBSetup\Dump\IrvingReport\Dump\IrvingReport\OUT\7200
IrvingReport_DummyFileOUT = D:\DBBSetup\Dump\IrvingReport\IrvingReport_MDW\Out
EnvironmentName  =  UAT
IsEmbReportSplitByInsId  =  YES

DRIVER = SQL Server Native Client 11.0
AccountUpdate_FileIN  =  D:\DBBSetup\Dump\AccountParametersUpdates\InputFolder
AccountUpdate_FileERROR  =  D:\DBBSetup\Dump\AccountParametersUpdates\ErrorFolder
AccountUpdate_FileLOG  =  D:\DBBSetup\Dump\AccountParametersUpdates\LogFolder
AccountUpdate_FileOUT  =  D:\DBBSetup\Dump\AccountParametersUpdates\OutFolder
AccountUpdate_EmptyFolder  =  D:\DBBSetup\Dump\AccountParametersUpdates\EmptyFolder
AccountUpdate_DebugMode  =  D:\DBBSetup\Dump\AccountParametersUpdates\EmptyFolder
# This is new tag using for only JAZZ environment above fields may already presents.
ReportTime  =  6

DataQualityControlEmail_Receiver  = platsupport@corecard.com
#[MilkReplaySchedulesUtility]
RetailInputFile = D:\DBBSetup\Dump\MilkReplaySchedules\INPUT
RetailErrorFile = D:\DBBSetup\Dump\MilkReplaySchedules\ERROR
RetailOutFile = D:\DBBSetup\Dump\MilkReplaySchedules\OUT
RetailLogFile = D:\DBBSetup\Dump\MilkReplaySchedules\LOG
RetailInstitutionID = 6969
RetailEnvironment = UAT
RetailExceptionFile = D:\DBBSetup\Dump\MilkReplaySchedules\EXCEPTION
RetailExceptionFilePrefix = EXCP_
RetailExceptionFileSuffix = _PODID_
BatchCount = 10000
AccountNumberCheck = 1
RetailGeneratedFile = D:\DBBSetup\Dump\MilkReplaySchedules\GENERATED
RetailGeneratedOutputFile = D:\DBBSetup\Dump\MilkReplaySchedules\OUT\GENERATED

#[PaymentHoldSetup]
POTBInputFile = D:\DBBSetup\Dump\POTB\INPUT
POTBErrorFile = D:\DBBSetup\Dump\POTB\OUTPUT
POTBOutFile = D:\DBBSetup\Dump\POTB\OUT
POTBLogFile = D:\DBBSetup\Dump\POTB\LOG
POTBExceptionFile = D:\DBBSetup\Dump\POTB\EXCEPTION
POTBExceptionPrefix = EXCP_
POTBExceptionSuffix = _PODID_
POTBIdentifier = ACCOUNTNUMBER
POTBPolicy = G2
POTBEnvironment = UAT
POTBInstitutionID = 6969

#Reward Target List WhiteListing
TargetListIN  =  D:\DBBSetup\Dump\Plat\TargetList\IN
TargetListOUT  =  D:\DBBSetup\Dump\Plat\TargetList\OUT
TargetListResponse  =  D:\DBBSetup\Dump\Plat\TargetList\Response
TargetListLOG  =  D:\DBBSetup\Dump\Plat\TargetList\LOG
TargetListERROR  =  D:\DBBSetup\Dump\Plat\TargetList\ERROR
EmpfileThreshhold  =  22:00
DisableRuleFileLOG  =  D:\Application\DUMP\TargetList\Log
################# Below section must be at bottom of configure file #####################
# alert receiver mail Ids can be different for each process
# This section will use to keep alert receiver mail Ids separate for each process

DayDiff = 0
CBR_PreTransmission  =  D:\DBBSetup\Dump\Plat\CBR\CBReporting\PreTransmissionReport
CBR_IDTheftRecon  D:\DBBSetup\Dump\Plat\CBR\CBReporting\IDTheftReconReport
DB_Server_NAME_RPT  = CCRPTLIST1
DB_DSN_NAME_RPT  = LISTRPT
post_dbms_login_RPT  = 
post_dbms_passwd_RPT  = 
# Reporting Database names
DBName_CI_RPT  = CCGS_RPT_CoreIssue
DBName_CC_RPT  = CCGS_RPT_CoreCollect
DBName_CL_RPT  = CCGS_RPT_CoreLibrary
DBName_CAuth_RPT  = CCGS_RPT_CoreAuth
DBName_CoreApp_RPT  = CCGS_RPT_CoreApp
DBName_CoreCredit_RPT  = CCGS_RPT_CoreCredit
# EmbossingEncrypted Start variable Code
EmbossingEncrypted_OUT  =  D:\DBBSetup\Dump\EmbossingEncrypted\EmbossingEncrypted_OUT
EmbossingEncrypted_Log  =  D:\DBBSetup\Dump\EmbossingEncrypted\EmbossingEncrypted_Log
# If IsRollbackRequired is 1 that means need to rollback and 0 for as per BAU process (PANHash64 AS OLDPANHASH,PANHashKey2 AS NEWPANHASH)
IsRollbackRequired  =  0
[TxnHistArch_TSDBO]
LogFilePath  =  D:\DBBSetup\Dump\TSDBO\LOG
IncomingFiles  =  D:\DBBSetup\Dump\TSDBO\FilePath\IncomingFiles
OutgoingFiles  =  D:\DBBSetup\Dump\TSDBO\FilePath\OutgoingFiles
DailyMetaDataFilePath  =  D:\DBBSetup\Dump\TSDBO\FilePath\DailyMetaDataFile
IncomingFiles_ErrorSummary  =  D:\DBBSetup\Dump\TSDBO\FilePath\IncomingFiles\Error
AccountIncomingFiles  =  D:\DBBSetup\Dump\TSDBO\FilePath\Account\IncomingFiles
AccountOutgoingFiles  =  D:\DBBSetup\Dump\TSDBO\FilePath\Account\OutgoingFiles
AccountIncomingOutFiles  =  D:\DBBSetup\Dump\TSDBO\FilePath\Account\IncomingOutFiles
MailSub  =  [PLAT PROD POD2] - [TSDBO Data Extraction] - [{AlertType}]
MailTo  = platalertsupport@corecard.com, platsd@corecard.com
MailCC  = platalertsupport@corecard.com, platsd@corecard.com
[StatementFingerPrintBatch]
InputDir  =  D:\DBBSetup\Dump\StatementFingerPrintBatch\INPUT
OutputDir  =  D:\DBBSetup\Dump\StatementFingerPrintBatch\OUTPUT
ErrorDir  =  D:\DBBSetup\Dump\StatementFingerPrintBatch\ERROR
LogDir  =  D:\DBBSetup\Dump\StatementFingerPrintBatch\LOG
alert_email_receiver  =  Pod2ConfigTeam@corecard.com,platalertsupport@corecard.com, platsd@corecard.com, PlatOperation@corecard.com
batchcount  =  500
archive  =  True
RenameInputFile  =  False

[ACHProcess]
alert_email_receiver = Pod2ConfigTeam@corecard.com,platalertsupport@corecard.com, platsd@corecard.com, PlatOperation@corecard.com

[ACHISOReturn]
alert_email_receiver = Pod2ConfigTeam@corecard.com,platalertsupport@corecard.com, platsd@corecard.com, PlatOperation@corecard.com

[LockBox]
alert_email_receiver = Pod2ConfigTeam@corecard.com,platalertsupport@corecard.com, platsd@corecard.com, PlatOperation@corecard.com

[BillPay]
alert_email_receiver = Pod2ConfigTeam@corecard.com,platalertsupport@corecard.com, platsd@corecard.com, PlatOperation@corecard.com

[NACHAReturn]
alert_email_receiver = Pod2ConfigTeam@corecard.com,platalertsupport@corecard.com, platsd@corecard.com, PlatOperation@corecard.com

[PaymentHoldSetup]
alert_email_receiver = Pod2ConfigTeam@corecard.com,platalertsupport@corecard.com, platsd@corecard.com, PlatOperation@corecard.com

[MilkReplaySchedulesUtility]
alert_email_receiver = Pod2ConfigTeam@corecard.com,platalertsupport@corecard.com, platsd@corecard.com, PlatOperation@corecard.com

[DataQualityControlEmail_Receiver]  
DataQualityControlEmail_Receiver =  Pod2ConfigTeam@corecard.com, platalertsupport@corecard.com, platsd@corecard.com, PlatOperation@corecard.com,platsupport@corecard.com
#########################################################################################